version: '3.1'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    tty: true
    depends_on:
      - api_mongo
  api_mongo:
    image: mongo:4.4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./dbdata:/data/db
      - ./configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  api_mongo-express:
    image: mongo-express:0.54.0
    restart: always
    links:
      - api_mongo:mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - api_mongo

